//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FurnitureProductionSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.ProductionProcess = new HashSet<ProductionProcess>();
        }
    
        public int ProductID { get; set; }
        public string Name { get; set; }
        public string Article { get; set; }
        public decimal MinPartnerPrice { get; set; }
        public int ProductTypeID { get; set; }
        public int MaterialID { get; set; }
    
        public virtual Materials Materials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductionProcess> ProductionProcess { get; set; }
        public virtual ProductTypes ProductTypes { get; set; }
    }
}
